FROM envoyproxy/envoy-alpine:v1.14.4

ARG ssl_certs_dir=/etc/ssl-certs
WORKDIR $ssl_certs_dir

VOLUME $root_dir/localhost
VOLUME $root_dir/certbot

EXPOSE 443
EXPOSE 80

CMD /usr/local/bin/envoy -c /etc/envoy-proxy.dev.yaml --service-cluster envoy-proxy
